name: Setup Python with uv
description: Setup Python with uv and install dependencies

runs:
    using: composite
    steps:
        - name: Install uv
          uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244 # v7.1.4
          with:
              version-file: .tool-versions
              enable-cache: true
              save-cache: ${{ github.ref == 'refs/heads/main' }}

        - name: Set up Python
          shell: bash
          run: uv python install

        - name: Install dependencies
          shell: bash
          run: |
              uv sync --dev --frozen
